# -----------------------------------------------------------
# 
# Complementary functions to perform FEWS config related tasks
# 
# -----------------------------------------------------------
import os
import shutil

def overwrite_dir(dir):
    """Checks if folder exists and if exists delete folder and
    all contents before making the folder.

    Arguments:
    dir {string} -- path of the folder to make with os.makedir
    """
    if os.path.exists(dir):
        shutil.rmtree(dir)
    os.makedirs(dir)

def makedir_ifnotexist(dir):
    if not os.path.exists(dir):
        os.makedirs(os.path.dirname(dir))

def create_fews_folder_structure(rootpath, directory_list):
    """This creates an empty folder structure at the rootpath location
    as listed in the directory_list as subfolders to the Config folder

    Arguments:
        fpath {string} -- Root folder for the folder structure
        directory_list {list} -- list of paths and subpaths to add
    """ 
    configpath = os.path.join(rootpath,'Config')
    overwrite_dir(configpath)
    for directory in directory_list:
        config_subpath = os.path.join(configpath,directory)
        if os.path.exists(config_subpath):
            overwrite_dir(config_subpath)
        else:
            os.makedirs(config_subpath)

def moveTree(sourceRoot, destRoot):
    if not os.path.exists(destRoot):
        return False
    ok = True
    for path, dirs, files in os.walk(sourceRoot):
        relPath = os.path.relpath(path, sourceRoot)
        destPath = os.path.join(destRoot, relPath)
        if not os.path.exists(destPath):
            os.makedirs(destPath)
        for file in files:
            destFile = os.path.join(destPath, file)
            if os.path.isfile(destFile):
                ok = False
                continue
            srcFile = os.path.join(path, file)
            shutil.copy(srcFile, destFile)
    return ok

def mergefews_scripted_default(dir_scripted,dir_default,dir_combined):
    """Takes the content of the default (manually scripted) FEWS config
    and the content of the scripted FEWS config (generated by scripts) and
    copies all files in one config. Existing config is overwritten when a new
    file is added to a particular folder.

    Arguments:
        dir_scripted {string} -- path to the folder (REGIONHOME) of the scripted part of the config
        dir_default {string} -- path to the root folder (REGIONHOME) of the default part of the config
        dir_combined {string} -- path to the root folder (REGIONHOME) combined config
    """    
    default_dir_list = os.listdir(dir_default)
    for default_dir in default_dir_list:
        target_dir_combined = os.path.join(dir_combined,default_dir)
        source_dir = os.path.join(dir_default,default_dir)
        if os.path.exists(target_dir_combined):
            shutil.rmtree(target_dir_combined)
        shutil.copytree(source_dir,target_dir_combined)

    scripted_dir_list = os.listdir(dir_scripted)
    moveTree(dir_scripted,dir_combined)
